### ISSUE TITLE
auto page refresh

### ISSUE THREAD

**Issue by majidmp97** [G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory#1]
hello
can you change code for auto refresh page look like this source

[https://github.com/projetsdiy/ESP8266WebServer-Bootstrap-Bootswatch]

**Comment by G6EJD** [comment]
Just add an html refresh command like this https://www.w3schools.com/TAGS/att_meta_http_equiv.asp

**Comment by G6EJD** [comment]
The esp can’t act like a PC but I have provided a SD read write routine

**Comment by majidmp97** [comment]
thank you  i well try that
