### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by smiffycom** [G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory#3]
Looked like just what I was looking for, downloaded BUT;
It doesn't compile, too many missing libraries, undeclared variables, lots of does not name a type and other errors.

Gave up in the end

**Comment by G6EJD** [comment]
Well I assume you downloaded all the support files - sounds like you didn’t. Your sketch folder needs to contain all the other files css.h, sys_variables.h, network.h etc - does it?

**Comment by smiffycom** [comment]
importing the zip had failed, it didnt like the directory name in the Zip file, sorted now thanks
