### ISSUE TITLE
Filenames with spaces has wrong filename

### ISSUE THREAD

**Issue by Primus007** [G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory#4]
i am using the ESP_File_Download_Upload_Dir_Strream_V03.ino
All works fine. 
But if a file on sd card with spaces "photo 01.jpg" then the download filename is only "photo.jpg" 
It breaks the filename on the first space. And the fileextension is not correct also.

if i Serial.println("FILENMAME: " + filename); in the SD_file_download(String filename) the filename is ok. But the download filename of the file is not ok.

How can i fix it?

**Comment by G6EJD** [comment]
What’s going wrong is the use of file names that do not correspond to the 8.3 standard with only characters 0-9Az,  spaces can be replaced with an underscore. Eg image_01.jpg
The MS-DOS file name standard is not that used on a modern filing system.
