### ISSUE TITLE
Does not work at all ESP-32S (esp-wroom32 NodeMCU v1.1)

### ISSUE THREAD

**Issue by u-can-call-me-My-Master** [G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory#5]
Hi G6EJD,

Thank you very much for your example. 

I tried to use SD card example with my ESP-32S (NodeMCU v1.1) and 2.2 SPI Display ILI9225. Its shield has SD card adapter like this:
![image](https://user-images.githubusercontent.com/66565516/83974721-0d7ef000-a8f8-11ea-9a40-8036e95ff5cb.png)
So, I wired it in parallel wit SPI pins of the display (HSPI pins of esp32) and CS to pin #5. 
I run the code with no probs. Server starts work as well. 
However, when I am trying click "Directory" button at server's page the esp32 gots restarting. Same with File Upload, Download and etc.
By debugging I could find out the fatal jumps out in `void PrintDirectory (const char * dirname, uint8_t levels)` function at the line 
`File file = root.openNextFile();` 
It is the very moment when the mcu gets rebooted.. 
I would be very grateful for your kind help..

**Comment by G6EJD** [comment]
You don’t mention that your using 2 x CS, one fit the display and one for the SD card and the SD.begin(pin) references the SD card CS. The inbuilt SD card driver does not work as far as I know it’s a long standing problem. You should try an SD card example by itself to prove your wiring is correct before going for a combined solution like this, I think you’ve proven the display side works ok.

**Comment by u-can-call-me-My-Master** [comment]
Thank for the reply. Here the funny part. (In advance I think problems with the code, perhaps, in new Libs ). 
Of course I did check the SD part, I even play videos from the SD. The problem is different.  Look, I tried this code from the sd example and it works for sure: 
```
void listDir(fs::FS &fs, const char * dirname, uint8_t levels){
    Serial.printf("Listing directory: %s\n", dirname);

    File root = fs.open(dirname);
    if(!root){
        Serial.println("Failed to open directory");
        return;
    }
    if(!root.isDirectory()){
        Serial.println("Not a directory");
        return;
    }

    File file = root.openNextFile();
    while(file){
        if(file.isDirectory()){
            Serial.print("  DIR : ");
            Serial.println(file.name());
            if(levels){
                listDir(fs, file.name(), levels -1);
            }
        } else {
            Serial.print("  FILE: ");
            Serial.print(file.name());
            Serial.print("  SIZE: ");
            Serial.println(file.size());
        }
        file = root.openNextFile();
    }
}

```
This code is works perfectly. And it uses **FS.h** which I do not find in yours, by the way. Let's dig deeper!
As I said before the problem in line witn `openNextFile();` no need to be nerd to understand and see the difference that the problem with SD object. We initialize it in void setup() function. And as we can see we transfer the address of SD itself to `listDir` function so there is no problem - it has its instance. 
**On the contrary,** with your functions there is no link to the origin instance of SD as argument of functions` SD_dir `and `PrintDirectory()` . I think it does not wok because of that for sure. Thus, I tried to put it like this: 
```

void printDirectory(const char * dirname, uint8_t levels){

   SPIClass spi = SPIClass(VSPI);
   spi.begin(14, 12, 13, 5);
  if (!SD.begin(SS, spi, 80000000))
  {
    Serial.println("Card Mount Failed");
    return;
  }

  File root = SD.open(dirname);
...

```

And wow! It works!!! But I am not an insane to initiate SD.begin() in each sever function )))). Moreover, I am not that experienced and could not add an argument parameter to server functions i.e. `server.on("server.on("/dir",      SD_dir(fs::FS &fs));")` just to make it work like with Espressif example of listDir function. I thought the way to resovle this issue is to some how make SD instance global...? Could you please help me to make it work...thanks!

**Comment by G6EJD** [comment]
Your problem is not using a separate CS for the SD card in that example your using SS which is pin 5, so in my code choose and use another pin for SD card CS say 15 and make sure that’s wired to the SD CS pin on a seller are row on the display

**Comment by u-can-call-me-My-Master** [comment]
I am using different CS's for SD and Display: 

```
#define TFT_CS 15
#define TFT_DC 25
#define TFT_RST 26
#define SS 5  

Arduino_DataBus *bus = new Arduino_ESP32SPI(TFT_DC, TFT_CS, 14 /* SCK */, 13 /* MOSI */, -1 /* MISO */, VSPI /* spi_num */);
// ILI9225 LCD 176x220
Arduino_ILI9225 *gfx = new Arduino_ILI9225(bus, TFT_RST, 1 /* rotation */);

```
and
```

SPIClass spi = SPIClass(VSPI);
 spi.begin(14, 12, 13, 5);
 if (!SD.begin(SS, spi, 80000000))
{
  Serial.println("Card Mount Failed");
  return;
}

```
And then why it works with `listDir(fs::FS &fs, ..)` function which called from `void setup()`? 
And works if I put `SD.begin(5)` directly inside `PrintDirectory("\", 0)` function instead of putting it in `void setup ()`?

**Comment by u-can-call-me-My-Master** [comment]
Also I have just done the SD_test from inbuilt ESP32 examples separately as you suggested before. With next config: 
 ```
SPIClass spi = SPIClass(VSPI);
 spi.begin(14, 12, 13, 5);
 if (!SD.begin(SS, spi, 80000000))
{
  Serial.println("Card Mount Failed");
  return;
}
```
**Test was completed with success.** 
```
22:15:29.988 -> SD Card Type: SDSC
22:15:29.988 -> SD Card Size: 1935MB
22:15:29.988 -> Listing directory: /
22:15:29.988 ->   DIR : /System Volume Information
22:15:30.095 -> Creating Dir: /mydir
22:15:30.884 -> Dir created
22:15:30.884 -> Listing directory: /
22:15:30.884 ->   DIR : /System Volume Information
22:15:30.986 ->   DIR : /mydir
22:15:30.986 -> Removing Dir: /mydir
22:15:31.157 -> Dir removed
**... and so on!**
```

**Comment by u-can-call-me-My-Master** [comment]
Just your code with server, but with my config for spi:
```
22:36:33.682 -> Connected to .... Use IP address: 192.168.0.88
22:36:33.682 -> Initializing SD card...Card initialised... file access enabled...
22:36:33.682 -> HTTP server started **then I clicked to show directory at the webpage.. and**
22:37:01.218 -> /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1443 (xQueueGenericReceive)- assert failed!
22:37:01.218 -> abort() was called at PC 0x40088ac5 on core 1
22:37:01.218 -> 
22:37:01.218 -> Backtrace: 0x4008c674:0x3ffb17e0 0x4008c8a5:0x3ffb1800 0x40088ac5:0x3ffb1820 0x400da8cd:0x3ffb1860 0x400d9f15:0x3ffb1880 0x400d91f5:0x3ffb18b0 0x400d969d:0x3ffb18e0 0x400f5296:0x3ffb1920 0x400f1a61:0x3ffb1940 0x400f2520:0x3ffb1960 0x400f3d05:0x3ffb1980 0x400f49d6:0x3ffb1bb0 0x400f4a40:0x3ffb1bd0 0x40110812:0x3ffb1c00 0x400d8d84:0x3ffb1c20 0x400d85f2:0x3ffb1ca0 0x400d2eb5:0x3ffb1cd0 0x400d36fa:0x3ffb1e50 0x40151fad:0x3ffb1e90 0x400d602b:0x3ffb1eb0 0x400d60d1:0x3ffb1ed0 0x400d613e:0x3ffb1f00 0x400d64a5:0x3ffb1f40 0x400d1b1a:0x3ffb1f90 0x400dbee9:0x3ffb1fb0 0x40088dbd:0x3ffb1fd0
22:37:01.287 -> 
22:37:01.287 -> Rebooting...
22:37:01.287 -> ets Jun  8 2016 00:22:57
22:37:01.287 -> 
22:37:01.287 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
22:37:01.287 -> configsip: 0, SPIWP:0xee
22:37:01.287 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:37:01.287 -> mode:DIO, clock div:1
22:37:01.287 -> load:0x3fff0018,len:4
22:37:01.287 -> load:0x3fff001c,len:1044
22:37:01.321 -> load:0x40078000,len:8896
22:37:01.321 -> load:0x40080400,len:5816
22:37:01.321 -> entry 0x400806ac
22:37:01.730 -> Connecting ...
22:37:04.632 -> 
22:37:04.632 -> Connected to... Use IP address: 192.168.0.88
22:37:04.632 -> Initializing SD card...Card initialised... file access enabled...
22:37:04.632 -> HTTP server started
```
you can see that it got restarted ..

**Comment by G6EJD** [comment]
You can’t use two instances of the SPI bus all devices must share the SPI bus lines apart from the CS lines so you need to wire the display and SD card in parallel and select the devices withe the CS, this is why your getting a crash. 
ESP32 MOSI to SD MOSI and TFT MOSI
ESP32 MISO to SD MISO no need for TFT to be connected as no data out
ESP32 DC to SD DC and TFT DC
ESP32 CLK to SD CLK and TFT CLK
And so on
ESP32 TFT CS to TFT CS
ESP32 SD CS to SD CS

**Comment by u-can-call-me-My-Master** [comment]
I did wire them in parallel ........ I use HSPI pins: 13, 14, 15(cs_tft) for the TFT display and use 12, 13,14, 5(cs_sd) for the sd... 
Why then I could play a video from the SD card and it's not getting crashed?

**Comment by G6EJD** [comment]
Yes but the compiler does not support two instances of the SPI bus, there can be only one. I’m not aware of an SPI library that supports multi-threading and re-entrant usage. Your trying to do something that is not supported with the Arduino IDE?

**Comment by G6EJD** [comment]
Wiring in parallel means the same single bus pins.

**Comment by u-can-call-me-My-Master** [comment]
Okay. It might be closer to the problem.  How can I make work you project separately  (no combine solution) but with sd card on this tft display shield? 
Yes parallel means that I connected "clock" wires from sd and tft to the same pin of eps32 and mosi like that. There is no DC wire for the sd though.

**Comment by G6EJD** [comment]
There’s no code issue with my code, you’ve been trying to do something that the compiler does not support.

As with all these displays/boards including touch, you must wire the SPI bus to all devices so TFT and SD and if used Touch then separate them and select each with a CS line for each, if then works.

**Comment by u-can-call-me-My-Master** [comment]
Thank you very much for your assistance.  By the way,  

> Yes but the compiler does not support two instances of the SPI bus, there can be only one.

I guess, it is not fully correct because:
```
/* The ESP32 has four SPi buses, however as of right now only two of
 * them are available to use, HSPI and VSPI. Simply using the SPI API 
 * as illustrated in Arduino examples will use VSPI, leaving HSPI unused.
 * 
 * However if we simply intialise two instance of the SPI class for both
 * of these buses both can be used. However when just using these the Arduino
 * way only will actually be outputting at a time.
 * 
 * Logic analyser capture is in the same folder as this example as
 * "multiple_bus_output.png"
 * 
 * created 30/04/2018 by Alistair Symonds
 */
#include <SPI.h>

// Define ALTERNATE_PINS to use non-standard GPIO pins for SPI bus

#ifdef ALTERNATE_PINS
  #define VSPI_MISO   2
  #define VSPI_MOSI   4
  #define VSPI_SCLK   0
  #define VSPI_SS     33

  #define HSPI_MISO   26
  #define HSPI_MOSI   27
  #define HSPI_SCLK   25
  #define HSPI_SS     32
#else
  #define VSPI_MISO   MISO
  #define VSPI_MOSI   MOSI
  #define VSPI_SCLK   SCK
  #define VSPI_SS     SS

  #define HSPI_MISO   12
  #define HSPI_MOSI   13
  #define HSPI_SCLK   14
  #define HSPI_SS     15
#endif

static const int spiClk = 1000000; // 1 MHz

//uninitalised pointers to SPI objects
SPIClass * vspi = NULL;
SPIClass * hspi = NULL;

void setup() {
  //initialise two instances of the SPIClass attached to VSPI and HSPI respectively
  vspi = new SPIClass(VSPI);
  hspi = new SPIClass(HSPI);
  
  //clock miso mosi ss

#ifndef ALTERNATE_PINS
  //initialise vspi with default pins
  //SCLK = 18, MISO = 19, MOSI = 23, SS = 5
  vspi->begin();
#else
  //alternatively route through GPIO pins of your choice
  vspi->begin(VSPI_SCLK, VSPI_MISO, VSPI_MOSI, VSPI_SS); //SCLK, MISO, MOSI, SS
#endif

#ifndef ALTERNATE_PINS
  //initialise hspi with default pins
  //SCLK = 14, MISO = 12, MOSI = 13, SS = 15
  hspi->begin();
#else
  //alternatively route through GPIO pins
  hspi->begin(HSPI_SCLK, HSPI_MISO, HSPI_MOSI, HSPI_SS); //SCLK, MISO, MOSI, SS
#endif

  //set up slave select pins as outputs as the Arduino API
  //doesn't handle automatically pulling SS low
  pinMode(VSPI_SS, OUTPUT); //VSPI SS
  pinMode(HSPI_SS, OUTPUT); //HSPI SS

}

// the loop function runs over and over again until power down or reset
void loop() {
  //use the SPI buses
  vspiCommand();
  hspiCommand();
  delay(100);
}

void vspiCommand() {
  byte data = 0b01010101; // junk data to illustrate usage

  //use it as you would the regular arduino SPI API
  vspi->beginTransaction(SPISettings(spiClk, MSBFIRST, SPI_MODE0));
  digitalWrite(VSPI_SS, LOW); //pull SS slow to prep other end for transfer
  vspi->transfer(data);  
  digitalWrite(VSPI_SS, HIGH); //pull ss high to signify end of data transfer
  vspi->endTransaction();
}

void hspiCommand() {
  byte stuff = 0b11001100;
  
  hspi->beginTransaction(SPISettings(spiClk, MSBFIRST, SPI_MODE0));
  digitalWrite(HSPI_SS, LOW);
  hspi->transfer(stuff);
  digitalWrite(HSPI_SS, HIGH);
  hspi->endTransaction();
}
```
It does support, please refer to the example by espressif "esp32->SPI->SPI_Multiple_Buses.  [https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/examples/SPI_Multiple_Buses/SPI_Multiple_Buses.ino](url)
May be it was not before, but now it's true (since 2018).
Anyways, again thank you very much for your assistance, you replied really fast and were not apathetic to my questions. Big respect.  I could manage the problem.

P.S. Is there a way to speed up the file upload to the server? And could it use "ESPAsyncWebServer.h"? As far as I understand it wouldn't need to put `server.handleClient();` in the loop.
