### ISSUE TITLE
Home page just show file sizes up to 1023b

### ISSUE THREAD

**Issue by cacs200281** [G6EJD/ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory#7]
Hello,

I'm trying to upload several files with different sizes.
When I send a file with size > 1023b I am getting 0 b size on the home page.
I am running the code on a ESP32 board(DOIT dev kit v1).
How can I solve it please?
Thanks!

**Comment by G6EJD** [comment]
It’s an issue with the Asynchronous WebServer library, sorry you need to raise the issue with Espressif
